CREATE TABLE label
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_label PRIMARY KEY (id)
);

CREATE TABLE labels_posts
(
    label_id BIGINT NOT NULL,
    post_id  BIGINT NOT NULL
);

CREATE TABLE post
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content    VARCHAR(255),
    created    TIMESTAMP WITHOUT TIME ZONE,
    updated    TIMESTAMP WITHOUT TIME ZONE,
    postStatus SMALLINT,
    writer_id  BIGINT,
    CONSTRAINT pk_post PRIMARY KEY (id)
);

CREATE TABLE writer
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstName VARCHAR(255),
    lastName  VARCHAR(255),
    CONSTRAINT pk_writer PRIMARY KEY (id)
);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_WRITER FOREIGN KEY (writer_id) REFERENCES writer (id);

ALTER TABLE labels_posts
    ADD CONSTRAINT fk_labpos_on_label FOREIGN KEY (label_id) REFERENCES label (id);

ALTER TABLE labels_posts
    ADD CONSTRAINT fk_labpos_on_post FOREIGN KEY (post_id) REFERENCES post (id);